from xlwt import Workbook, easyxf

book = Workbook()

sheet = book.add_sheet('Color')

sheet.write(0, 0, 'aqua', easyxf('pattern: pattern solid, fore_colour aqua'))
sheet.write(1, 0, 'black', easyxf('pattern: pattern solid, fore_colour black'))
sheet.write(2, 0, 'blue', easyxf('pattern: pattern solid, fore_colour blue'))
sheet.write(3, 0, 'blue_gray', easyxf('pattern: pattern solid, fore_colour blue_gray'))
sheet.write(4, 0, 'bright_green', easyxf('pattern: pattern solid, fore_colour bright_green'))
sheet.write(5, 0, 'brown', easyxf('pattern: pattern solid, fore_colour brown'))
sheet.write(6, 0, 'coral', easyxf('pattern: pattern solid, fore_colour coral'))
sheet.write(7, 0, 'cyan_ega', easyxf('pattern: pattern solid, fore_colour cyan_ega'))
sheet.write(8, 0, 'dark_blue', easyxf('pattern: pattern solid, fore_colour dark_blue'))
sheet.write(9, 0, 'dark_blue_ega', easyxf('pattern: pattern solid, fore_colour dark_blue_ega'))
sheet.write(10, 0, 'dark_green', easyxf('pattern: pattern solid, fore_colour dark_green'))
sheet.write(11, 0, 'dark_green_ega', easyxf('pattern: pattern solid, fore_colour dark_green_ega'))
sheet.write(12, 0, 'dark_purple', easyxf('pattern: pattern solid, fore_colour dark_purple'))
sheet.write(13, 0, 'dark_red', easyxf('pattern: pattern solid, fore_colour dark_red'))

sheet.write(0, 1, 'dark_red_ega', easyxf('pattern: pattern solid, fore_colour dark_red_ega'))
sheet.write(1, 1, 'dark_teal', easyxf('pattern: pattern solid, fore_colour dark_teal'))
sheet.write(2, 1, 'dark_yellow', easyxf('pattern: pattern solid, fore_colour dark_yellow'))
sheet.write(3, 1, 'gold', easyxf('pattern: pattern solid, fore_colour gold'))
sheet.write(4, 1, 'gray_ega', easyxf('pattern: pattern solid, fore_colour gray_ega'))
sheet.write(5, 1, 'gray25', easyxf('pattern: pattern solid, fore_colour gray25'))
sheet.write(6, 1, 'gray40', easyxf('pattern: pattern solid, fore_colour gray40'))
sheet.write(7, 1, 'gray50', easyxf('pattern: pattern solid, fore_colour gray50'))
sheet.write(8, 1, 'gray80', easyxf('pattern: pattern solid, fore_colour gray80'))
sheet.write(9, 1, 'green', easyxf('pattern: pattern solid, fore_colour green'))
sheet.write(10, 1, 'ice_blue', easyxf('pattern: pattern solid, fore_colour ice_blue'))
sheet.write(11, 1, 'indigo', easyxf('pattern: pattern solid, fore_colour indigo'))
sheet.write(12, 1, 'ivory', easyxf('pattern: pattern solid, fore_colour ivory'))
sheet.write(13, 1, 'lavender', easyxf('pattern: pattern solid, fore_colour lavender'))

sheet.write(0, 2, 'light_blue', easyxf('pattern: pattern solid, fore_colour light_blue'))
sheet.write(1, 2, 'light_green', easyxf('pattern: pattern solid, fore_colour light_green'))
sheet.write(2, 2, 'light_orange', easyxf('pattern: pattern solid, fore_colour light_orange'))
sheet.write(3, 2, 'light_turquoise', easyxf('pattern: pattern solid, fore_colour light_turquoise'))
sheet.write(4, 2, 'light_yellow', easyxf('pattern: pattern solid, fore_colour light_yellow'))
sheet.write(5, 2, 'lime', easyxf('pattern: pattern solid, fore_colour lime'))
sheet.write(6, 2, 'magenta_ega', easyxf('pattern: pattern solid, fore_colour magenta_ega'))
sheet.write(7, 2, 'ocean_blue', easyxf('pattern: pattern solid, fore_colour ocean_blue'))
sheet.write(8, 2, 'olive_ega', easyxf('pattern: pattern solid, fore_colour olive_ega'))
sheet.write(9, 2, 'olive_green', easyxf('pattern: pattern solid, fore_colour olive_green'))
sheet.write(10, 2, 'orange', easyxf('pattern: pattern solid, fore_colour orange'))
sheet.write(11, 2, 'pale_blue', easyxf('pattern: pattern solid, fore_colour pale_blue'))
sheet.write(12, 2, 'periwinkle', easyxf('pattern: pattern solid, fore_colour periwinkle'))
sheet.write(13, 2, 'pink', easyxf('pattern: pattern solid, fore_colour pink'))

sheet.write(0, 3, 'plum', easyxf('pattern: pattern solid, fore_colour plum'))
sheet.write(1, 3, 'purple_ega', easyxf('pattern: pattern solid, fore_colour purple_ega'))
sheet.write(2, 3, 'red', easyxf('pattern: pattern solid, fore_colour red'))
sheet.write(3, 3, 'rose', easyxf('pattern: pattern solid, fore_colour rose'))
sheet.write(4, 3, 'sea_green', easyxf('pattern: pattern solid, fore_colour sea_green'))
sheet.write(5, 3, 'silver_ega', easyxf('pattern: pattern solid, fore_colour silver_ega'))
sheet.write(6, 3, 'sky_blue', easyxf('pattern: pattern solid, fore_colour sky_blue'))
sheet.write(7, 3, 'tan', easyxf('pattern: pattern solid, fore_colour tan'))
sheet.write(8, 3, 'teal', easyxf('pattern: pattern solid, fore_colour teal'))
sheet.write(9, 3, 'teal_ega', easyxf('pattern: pattern solid, fore_colour teal_ega'))
sheet.write(10, 3, 'turquoise', easyxf('pattern: pattern solid, fore_colour turquoise'))
sheet.write(11, 3, 'violet', easyxf('pattern: pattern solid, fore_colour violet'))
sheet.write(12, 3, 'white', easyxf('pattern: pattern solid, fore_colour white'))
sheet.write(13, 3, 'yellow', easyxf('pattern: pattern solid, fore_colour yellow'))

book.save('color.xls')