

from odoo.tests.common import TransactionCase



class TestResUsers(TransactionCase):


  def test_get_apple_key_and_secret(self):

    client_id, client_secret = self.env['res.users'].get_apple_key_and_secret()


  def test_do_validate_auth_apple(self):

    validate = self.env['res.users'].do_validate_auth_apple('eyJraWQiOiI4NkQ4OEtmIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoidGMubW90b3IuY29tIiwiZXhwIjoxNjA0MTA4OTY0LCJpYXQiOjE2MDQwMjI1NjQsInN1YiI6IjAwMTk5Ny44YjMwZTU3NGM3ZjM0NGQ4YmMzZWUyODJjYTU2NjZlYi4wNjUwIiwibm9uY2UiOiI5MmU2YTI4ZGY5ZmQ1NDcwMGFjMTFmMDBkYjBiMmM1NGYyNDM2ZTFkNTVmZGRmNjdmNTAxYzcwOTdlZGYzZTE5IiwiY19oYXNoIjoiYXlIdzdGa05MSENaTU5zbXpTbHN4QSIsImVtYWlsIjoiaG9hbmdob2lodXN0QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImF1dGhfdGltZSI6MTYwNDAyMjU2NCwibm9uY2Vfc3VwcG9ydGVkIjp0cnVlfQ.MruOYVSkFfe7A8DGln1EwajDROtDErwy-beiSbO7ZTAK-xgREFO5BJbyUgaNKXytUCbymVjWw6-7mJnl5yHlRyVeYBaRYrbTSevIeTNsCZZFqE7XUz6wTNNd15AMj8vRB44Vch6X5y-UQDIdBrQMGoU_vFVtewX4ihxS9bzrQzpMjWKuRWwv9q3XbCC_HE6ds872aIq1ZX9vSg0uGI0Q0vyTa4jj0PdskF2OZjHwzXwC_icaKtKbXp0DXxnZqw9pYkcVizlk7brqUAERLX6IAjD7mqRQOj0whtr_Ol295cnElA6o-x5HmC9g_KKZ9M3MvXnquYwueybHEV0RUaL4ig')

    print(validate)
