# -*- coding: utf-8 -*-
{
    'name': 'General Request ',
    'version': '1.0',
    'sequence': 1,
    'summary': 'Odoo 14 tổng hợp yêu cầu hàng bán',
    'description': """""",
    'category': 'Tutorials',
    'author': 'ERPViet',
    'maintainer': '',
    'website': 'https://erpviet.vn/',
    'license': 'LGPL-3',
    'depends': [
        'purchase',
        'stock',
        'report_xlsx',
        'ev_stock_transfer',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        # 'wizard/allotment_request_imp.xml',
        # 'wizard/genaral_product_group_imp.xml',
        # 'wizard/general_warehouse_group_imp.xml',
        'views/general_request_view.xml',
        'report/general_request_report.xml',
        'views/import_general_request.xml',
        # 'views/allotment_request.xml',
        # 'views/general_product_group.xml',
        # 'views/general_warehouse_group.xml',
        # 'report/allotment_request_report.xml',
        'views/menu_vies.xml',
    ],
    'demo': [],
    'qweb': [],
    'images': [''],
    'installable': True,
    'auto_install': False,
    'application': True,
}
